### ISSUE TITLE
Smelter's Pickaxe appears to be unbreakable

### ISSUE THREAD

**Issue by tjd2** [TheBusyBiscuit/Slimefun4#1251]
## Description (Required)
One of players on my server has Smelter's Pickaxe. He used it for very long time and it has got 1560/1561 durability.
He has enchanted it with Efficiency IV and Fortune III

## Steps to reproduce the Issue (Required)
1. Get Smelter's pickaxe
2. Try to use it as much as possible

## Expected behavior (Required)
I think it's supposed to break like normal diamond pickaxe. He has used it for like 3 days and he said, it's unbreakable.

## Server Log / Error Report
There are no errors in console.

## Environment (Required)
Minecraft version: 1.14.4 (PaperSpigot)
Slimefun vRC - 2 (git 4bb9abd2)
CSCoreLib vv1.6.1
PaperSpigot version: git-Paper-214

**Comment by WalshyDev** [comment]
We will not accept bug reports for the release candidate as they're most likely already fixed in the latest development build. Please try on [that build](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/), if the issue persists then open a new issue.

Also, update your CS-CoreLib - [Latest can be found here](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/).

**Comment by tjd2** [comment]
I will close it and try to update.
