### ISSUE TITLE
Detecting whether inventory belongs to backpack

### ISSUE THREAD

**Issue by mfnalex** [TheBusyBiscuit/Slimefun4#1918]
I am the author of ChestSort (www.chestsort.de) and I have been asked to add support for Slimefun's backpacks.

To do this, I will have to check if an instance of Inventory belongs to a backpack. Is there some way to do this using your API?

**Comment by TheBusyBiscuit** [comment]
There is not. Definitely no exposed way to do that.
But please don't abuse the bug tracker for this, we have a discord server for questions / requests.

Not even sure whether the current system would even allow something like that in the first place.
But it's open-source so there is little that a PR can't fix or add ;)
Maybe someone on discord has some thoughts on how you or them can implement it.

**Comment by mfnalex** [comment]
Sorry, I didnt mean to mark it as bug, but there was no other way to open an issue.

**Comment by TheBusyBiscuit** [comment]
Yeah, again we usually handle questions or requests over on discord: https://github.com/TheBusyBiscuit/Slimefun4#discord

Especially because I think that this may require a pull request to be made, I'd highly suggest you to ask someone there. I am sure someone over on discord may either help you with it or even pr it themselves.
