### ISSUE TITLE
Seismic axe and Elemental Staff - Strom works on protected areas

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#2207]
## Description (REQUIRED)

Seismic axe and Elemental Staff - Strom works on protected areas.
Example: Griefprevention claims
The entities can be killed this.

## Steps to reproduce the Issue (REQUIRED)

https://www.youtube.com/watch?v=_1TrQoLB2sw
https://www.youtube.com/watch?v=LH7h1lS4YOI

## Expected behavior (REQUIRED)

Seismic axe and Elemental Staff - Strom not work on protected areas

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.1
 - Slimefun Version: vDEV - 627 (git 7de9dd66)
 - CS-CoreLib Version: vDEV - 90 (git 9dd4a1cf)

**Comment by TheBusyBiscuit** [comment]
The Seismic Axe should be fixed in build "DEv - 632" and higher.

However with the Storm Staff there isn't really any sensible way to approach this. It simply comes down to how your protection plugin handles lightning strikes.
If it causes you any trouble, you should maybe consider disabling the Storm Staff in that case.

**Comment by andris155** [comment]
Thanks
