### ISSUE TITLE
Dual functionality Electric Ore Grinder

### ISSUE THREAD

**Issue by LeafyMitsuwa** [TheBusyBiscuit/Slimefun4#247]
## Description
The Electric Ore Grinder functions as both an ore grinder as well as a Grindstone. When placing Cobblestone into the input slot, the Electric Ore Grinder seems to only convert it into Gravel, ignoring the Cobblestone into Sand recipe from the Ore Crusher.

My educated guess would be that this is due to the fact that that particular recipe requires 8 Cobblestone in order to produce 1 Sand, and the Electric Ore Crusher only processes Cobblestone 1 at a time.

Whilst I do would not say that this is a bug, per definition, perhaps an implementation that allows players to choose how Cobblestone should be processed could be implemented? Perhaps via a direct redstone current, or a toggleable button in the GUI? Simply voicing thought here.

## Server Log
No errors reported.

## Environment
CS-CoreLib 1.5.14, Slimefun 4.1.6

**Comment by LeafyMitsuwa** [comment]
It does seem to grab 16 Netherrack at a time to create Sulfate. So, perhaps it could grab 8 Cobblestone as well, but perhaps favours the 1 Cobblestone -> 1 Gravel recipe over the 8 Cobblestone -> 1 Sand recipe.

**Comment by TheBusyBiscuit** [comment]
For anyone looking to do a PR on this:

https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/MiscSetup.java#L123-L149

This part needs to be rewritten with a List and a custom Comparator to favor recipes with greater input amounts.

**Comment by RedDeadSoul** [comment]
i like see it break other ores too like coal,diamond and others

**Comment by Liruxo** [comment]
I would like to report, that this "fix" currently breaks all automated Slimefun dust farms, because now Electric Ore Grinders are able to produce sand and not only gravel. E.g. before this, it was possible to just put a stack of cobblestone into the Electric Ore Grinder and it would produce a stack gravel. Now it just produces 8 Sand, which is unfortunately unusable for sifting. And making sure there is at all times only 7 or less cobblestone in the Electric Ore Grinder in an automated fashion is between very complicated and impossible.

Proposed Solutions:
1. Revert 65af683, or
2. Create two distinct electrical variants of Grindstone and Ore Grinder, or
3. Change the recipe of Sand, so it is for example is created out of 8 Gravel instead so that there aren't two "conflicting" cobblestone recipes

If necessary or wanted i can turn this into a full fledged new issue report

**Comment by TheBusyBiscuit** [comment]
@Liruxo Don't file a new issue for this, it is not a bug.
I added in a config option to dictate whether to use the new or old behaviour.

99cd14fa5f8471d7c506eacbaaee1ea2ba7c91fb

**Comment by unnamelesss** [comment]
@TheBusyBiscuit Is there an ingame way to fix this? The server I play on updated and this broke my dust farm. I dont have access to modify the config

**Comment by TheBusyBiscuit** [comment]
No... Settings are for admins, not Players.
