### ISSUE TITLE
Soulbound  Backpack Recipe Bug

### ISSUE THREAD

**Issue by kljigs500** [TheBusyBiscuit/Slimefun4#282]
## Description
IDs are already generated once the small backpack is made. But to make a soulbound backpack, you must have 'no' ID from a glided backpack,, thus making it impossible to craft since upgrading the backpack until glided backpack maintains the ID given. There were already reports by other users of the same issue. Although I failed to make screenshots because I was too focused on making slime fun machines.

## Server Log
No log (I'm a player of the server)

## Evidence / Proof
Recipe for small backpack
![2017-05-08_16 50 27](https://cloud.githubusercontent.com/assets/26787840/25797411/b0032c80-340f-11e7-9e38-72b1c32ea440.png)

Small backpack made automatically makes the ID.
![2017-05-08_16 50 31](https://cloud.githubusercontent.com/assets/26787840/25797413/b005ab4a-340f-11e7-9831-ee2bb08d6412.png)

Attempting to make soulbound backback via magical workbench.
![2017-05-08_16 54 20](https://cloud.githubusercontent.com/assets/26787840/25797412/b0053e9e-340f-11e7-894f-0c9ec30c950b.png)

Attempt failed as shown in the chatbox on the lower left
![2017-05-08_16 54 29](https://cloud.githubusercontent.com/assets/26787840/25797416/b01dfeac-340f-11e7-91ca-e657cb0c8cd7.png)

Attempting again to make a soulbound backpack, but this time with no ID given.
![2017-05-08_16 55 49](https://cloud.githubusercontent.com/assets/26787840/25797414/b0106594-340f-11e7-9054-9c9d184e4fee.png)

Soulbound backpack was a success.
![2017-05-08_16 56 04](https://cloud.githubusercontent.com/assets/26787840/25797415/b013fc90-340f-11e7-86d9-ac0d8c3b5253.png)

Therefore there must be no id for the crafting to work.

## Environment
Minecraft Version: 1.11.2
Server version: CraftBukkit v1_11_R1m (provided by admin)
CS-CoreLib v1.5.14 (provided by admin)
Slimefun: v4.1.8 (provided by admin)

Addons:
Exotic Garden: v1.6.3 (provided by admin)

**Comment by kljigs500** [comment]
it would be clearer if i recorded a video, but my upload is very slow and it takes a lot of time... I'll try to do better in the future. i hope the descriptions help at least so you can take a look. :) 

P.S. I was assisted by an admin who could /sf cheat

**Comment by comonier** [comment]
same here same version.... if helps.

**Comment by mrcoffee1026** [comment]
Verified.  Enhanced Crafting Table creates a small backpack with an ID.  However, the Automated Crafting Chamber Creates a small backpack without an ID as it's supposed to (unfortunately there's no method of crafting only one).  Please fix ASAP.

**Comment by mrcoffee1026** [comment]
Not just the small backpack... also pre-IDs the large backpack.  I won't test the rest,  my assumption is it pre-ids all of them.  Automated Crafting Chamber only method available at this time.

**Comment by TheBusyBiscuit** [comment]
> as it's supposed to

Wrong.

**Comment by mrcoffee1026** [comment]
OK?  Well then I didn't know you altered all of the other backpack recipes to accept ID-ed backpacks.  Please update the Soulbound recipe to take one too.

**Comment by Poslovitch** [comment]
In 4.1.6 changelog, it says the bug has been fixed.

However, we still can't upgrade backpacks. I'll investigate a bit more.

**Comment by Meta-Win** [comment]
I search a bit, and the problem are in the code of Magic Workbench.
I try to change the recipe of soulbound backpack to the Enhanced Crafting Table, and all worked ok.
Sorry, bad english.

**Comment by tuong10** [comment]
still bugging

**Comment by tuong10** [comment]
i change both but still can't craft it :(

**Comment by AquilaPrimacy** [comment]
The only way to fix this is to craft **backpacks without an ID** using the **Automatic Crafting Chamber.** You can use the **Gilded Backpack without an ID** on the **Magical Workbench** to craft the **Soulbound Backpack.**

**WARNING:** After crafting the prerequisite backpack without an ID, do not try to open it otherwise it will get an ID.

**Comment by mrcoffee1026** [comment]
Actually based on his last response to me in regards to this:  I'm not sure that it was ever intended for even the automatic crafting chamber to produce packs without IDs.  However, I LIKE THIS AS A FEATURE.  And backpacks without IDs play nice with other plugins like ChestShop if someone wants to produce and later sell their backpacks.  Using the Automatic Crafting Chamber is a valid work-around for the broken recipe, but the recipe for the Magic Workbench still needs to accept backpacks with IDs as well (as of a few builds ago, the Enhanced Crafting Table has accepted backpacks with IDs and has produced backpacks with IDs already assigned).  I have a pull request now that copied the logic for the enhanced crafting table recipe to the Magic Workbench recipe.  If they accept it, that will remedy the last broken recipe.  I did not copy the auto-ID-ing mechanism to this... looking it over, I'm not even sure why it works.  But I'm fine with the ID being assigned "on open" instead of "on craft", particularly since people don't tend to craft Soulbound Backpacks tremendously often.

**Comment by TheBusyBiscuit** [comment]
Adressed in #659
