### ISSUE TITLE
Backpack & Shulker Boxes

### ISSUE THREAD

**Issue by Loonyy** [TheBusyBiscuit/Slimefun4#295]
## Description
After updating to 4.1.8, you can't take shulker boxes out of backpacks. Specifically, soulbound backpacks.

## Environment
22.05 03:39:32 [Server] INFO CraftBukkit v1_11_R1
22.05 03:39:32 [Server] INFO CS-CoreLib v1.5.14
22.05 03:39:32 [Server] INFO Slimefun v4.1.8
22.05 03:39:32 [Server] INFO Installed Addons (2)
22.05 03:39:32 [Server] INFO ExoticGarden v1.6.3
22.05 03:39:32 [Server] INFO ElementumCore v2.2.0

**Comment by BlackBeltPanda** [comment]
Hover over the Shulker Box in the backpack and press a number key. It should remove the Shulker Box and transfer it to the corresponding hotbar slot.

**Comment by VoidAngel** [comment]
Backpacks have been updated to not allow the storage of Shulker boxes because it would create an issue with infinite inventory storage.

Also, BlackBeltPanda, I do not believe the number keys work like that anymore with backpacks.

**Comment by BlackBeltPanda** [comment]
@VoidAngel I tested it, it works for removing backpacks that were placed in Shulker Boxes prior to the update but doesn't work for re-inserting them.

**Comment by claer** [comment]
Note that there is still a bug for "transitioning" from an unsafe version to the updated backpacks. I have a case were a shulker box is inside a backpack due to previous sf version and cannot be extracted any more.
Dunno if this case should be ever considered in the code. If one dev is bored enough, he can look at it.
