### ISSUE TITLE
Grind Stone

### ISSUE THREAD

**Issue by NaomiTim** [TheBusyBiscuit/Slimefun4#334]
## Description
A few days ago some of my players have mentioned to me that for some reason the amount of blaze powder received after grinding it has lowered from 4 to 1. I've done nothing to the plugin or the server that should change anything with the amount given. However the day before it started happening the amount of blaze powder received was at it's normal amount which is 4.

## Evidence / Proof
http://prntscr.com/fmqzzq

## Environment
We need the EXACT VERSIONS of the Software you are using.
CraftBukkit v1_11_R1 (git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
CS-CoreLib v1.5.16
Slimefun V4.19

ExoticGarden v1.6.3
SlimefunOres v1.4.6
ExtraGear v1.1

**Comment by Poslovitch** [comment]
First of all, there is neither «v1.5.16» for CSCoreLib, nor «v4.19» for Slimefun.

You said you did nothing that «should change anything». But, as a bug can't appear without a reason, what did you do in the last 4 days? Did you update something? Did you modify a config file, regardless of the plugin?

**Comment by NaomiTim** [comment]
Oh sorry, I was meant to write down Slimefun V4.1.9(http://prntscr.com/fn5efy), I last updated slimefun and all the add-ons 6 days ago and I have not touched the slimefun configs.

**Comment by VoidAngel** [comment]
This happens because some recipe "output" itemstacks are handled incorrectly in the machine crafting, such as the enhanced crafting chamber, the electric ore grinder, etc. It also can happen with almost any recipe that can be crafted in an electric machine and that also has an output amount >1

The exact steps to replicate an example this bug would be:
1) Get an electric ore grinder and some blaze rods
2) Start grinding the blaze rods into blaze powder
3) Now the blaze powder comes out 4 at a time, but you need to somehow get an amount into the output slot that is not a factor of 64, so that when the last grind happens the full amount of blaze powder doesn't fit into the output slot.
4) Some blaze powder will be lost and the defined slimefun recipe output ItemStack amount will be changed until reload/restart.

I was thinking about making a pull request to fix this, but I'm not sure what the best way to handle the  AContainers would be. For the enhanced crafting chamber it would be pretty easy to just add in a ".clone()"
