### ISSUE TITLE
Items inside the Auto Enchanter and Disenchanter Dissapears on server restart?

### ISSUE THREAD

**Issue by NathanAdhitya** [TheBusyBiscuit/Slimefun4#50]
## Description
The title said about it, Basically, items in them disappear after a restart, which... is quite.... erm.. I lost a good amount of items due to that.

## Server Log
Logs not available since logs mostly gets wiped out after one.

## Evidence / Proof
Uhh, It's easy to try it out, I've had the problem on a public server, then tried out on a private one.

## Environment
- PaperSpigot (paperclip-916.2) on Minecraft 1.10.2
- CS-CoreLib_v1.5.12
- Slimefun 4.1.1

**Comment by Poslovitch** [comment]
It also appears with every AContainer.

**Comment by NathanAdhitya** [comment]
Looks like a critical bug, or is it? Doesn't happen with the Electric Furnace tho.... for some reason.

**Comment by NathanAdhitya** [comment]
Update: Looks like it's how late the SF Block Storage goes kick it on updating the list...?
Somehow, It reverted the Blocks from like a day mark, which is.... weird?

**Comment by VoidAngel** [comment]
I don't really understand the saving process, but I do know that
1) This happens with every AContainer like Poslovitch says. 
2) Another thing that I can replicate consistently is that if you, for example, make 64 magnets in the electric smeltery, remove them, leave the smeltery empty, and restart the server you will find the 64 magnets both in your inv and back inside the electric smeltery. (So basically a dupe)
Does it not update and save the block inventory to disk when you take items out? Or even on an interval?
3) Last, this is probably the same issue. I've found that when the server has a decent amount of cargo nodes (input or advanced output) they tend to reset a lot. By reset I mean lose their whitelist/inv/round robin mode settings. Its pretty random and I cant put an event to it like, for example, a server restart

**Comment by John000708** [comment]
Not happening to me.  When Slimefun disables it saves the current state of each block. Have you modified the config at all? Are there any errors from Slimefun when stopping the server?

**Comment by VoidAngel** [comment]
Hardy touched the config

`# 
# Name: Slimefun
# Author: mrCookieSlime
# 
# Do not modify the Config while the Server is running
# otherwise bad things might happen!
# 
# This Plugin also requires CS-CoreLib to run!
# If you don't have it installed already, its going to be
# automatically installed for you
# 
# This Plugin utilises an Auto-Updater. If you want to turn that off,
# simply set options -> auto-update to false
options:
  auto-update: false
  armor-update-interval: 10
  give-guide-on-first-join: true
  print-out-loading: false
  enable-armor-effects: true
  prefix: '&a&lSlimefun &7>'
  auto-save-delay-in-minutes: 10
  show-vanilla-recipes-in-guide: true
guide:
  default-view-book: false
URID:
  info-delay: 3000
  custom-ticker-delay: 12
  enable-tickers: true
items:
  talismans: true
  coolers: true
  backpacks: true
research-ranks:
- Chicken
- Cow
- Spider
- Villager
- Beginner
- Clumsy Student
- Unskilled Student
- Incompetent Student
- Student
- Clumsy Apprentice
- Apprentice
- Skilled Apprentice
- Upcoming Mage
- Excellent Mage
- Young Magician
- Incompetent Magician
- Common Magician
- Magician
- Proficient Magician
- Skilled Magician
- Accustomed Magician
- Great Magician
- Clumsy Wizard
- Wizard
- Common Wizard
- Skilled Wizard
- Great Wizard
- Impressive Wizard
- Young Master
- Clumsy Master
- Upcoming Master
- Competent Master
- Master
- Skilled Master
- Excellent Master
- Great Master
- Proficient Master
- The chosen One
`

No errors from slimefun at all.

It happens in batches too.. like the other day a bunch of the automated crafting chambers went and turned into normal workbenches (or perhaps just the ones that were loaded before the restart). When the bench was broken and replaced the same inventory was there from before.
A few days before that, a bunch of the android miners turned into heads.

Also, this didn't always happen. When the server first opened there was veeerry little block corruption. Now that the server is pretty established and a lot of players have played it happens quite frequently.

Is it because there are too many changes to save? Is there a time-out for saving blocks? Is the server able to keep up with the amount of changes that are talking place? Or maybe one of our data files became corrupt and is affecting everything around it? 

^ Dont answer that XD its just some thoughts.
I've been looking through the code myself looking for answers but I'm pretty new to java and the bukkit api so its been a slow process of elimination. I might try picking apart my server files on a test server to see if I can figure anything out

**Comment by NathanAdhitya** [comment]
I agree with him/her it happens quite often. Config Untouched.
Try, make some things, then after taking the things out /stop the server, then start it again. You'll see that the item is already in your inventory, while the item in the block is still right there.

**Comment by John000708** [comment]
@NathanAdhitya  or @VoidAngel  mind sending me your WHOLE data-storage/Slimefun folder (upload it somewhere)? I'll start digging into the saving code since I myself doesn't exactly know how that works :P

**Comment by VoidAngel** [comment]
Ill try but it will take a while for my dinosaur internet to download from my server and then upload XD

**Comment by NathanAdhitya** [comment]
@John000708 I don't think the block data storage matters tbh, because i was only trying it for testing purposes on my own server.... since the problem i had was on an actual public server.

**Comment by freethemice** [comment]
If the item is processing in any machine it will  disappear on restart. If it's in the inventory it will not.

**Comment by John000708** [comment]
Any more information on this? What @freethemice described is supposed to happen, is the issue @NathanAdhitya described still happening?

**Comment by NathanAdhitya** [comment]
Yup, https://github.com/TheBusyBiscuit/Slimefun4/issues/148

**Comment by Mitaykata** [comment]
Ok, confirmation from like 6 different slimefun servers - all public and almost each of them is a diff type of game - i.e. survival, factions, skyblock, etc.
After a server restart all SF blocks like Electric Ore Grinders, Electric Smelteries, Autoenchanters, Autodisenchanters, Ingot factories, Carbon Presses, Autoanvils and pretty much all reload their inventories from the previous time before the reset, regardless if you empty them just before the reset.
I think they save their last job which was they used for and if not used anymore just reload it after every server restart. It is mildly said "multidupe" because if you used your autosmeltery for making 64 reinforced ingots and carbon press for making 10 carbonados, along with your heated press chamber for making 10 blistering ingots, you will get them after every server restart. Most public servers restart once daily. So figure it out. I haven't confirmed if they "save" like a timestamp and reload from it or just the last finished job at all. Hope I helped some admins and devs and angered some players :)

**Comment by freethemice** [comment]
I think I posted this on the wrong thread before but to fix this
all you have to do to fix this is add the folowing at line 27 to rc\me\mrCookieSlime\Slimefun\api\inventory\BlockMenu.java****
@Override
public void open(Player... players){
super.open(players);
this.changes++;
}
This way every time someone looks or changes the inv on any mach. it flags it for save.

**Comment by TheBusyBiscuit** [comment]
@Mitaykata 
![](http://e.lvme.me/25hhabl.jpg)
