### ISSUE TITLE
Saw Mill not handling protection plugins correctly

### ISSUE THREAD

**Issue by BlackBeltPanda** [TheBusyBiscuit/Slimefun4#583]
## Description
Using the Saw Mill is very inconsistent unless the player has all permissions. It will work sometimes but mostly it won't do anything. As soon as the player has full perms, it seems to work fine. There are no errors in the console.

## Server Log
Log's too big for pastebin. =(

## Evidence / Proof
Video: https://www.youtube.com/watch?v=E1ur6vSkX1I

## Environment
MC: Paper v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.13
ChestTerminal v1.0

**Comment by Poslovitch** [comment]
I'm seeing two reasons for this to happen : 
1. There is an exception thrown when clicking on the Saw Mill (therefore we'd need logs)
2. Another plugin is interfering with the click event. (afaik, mcMMO doesn't affect anything related to Slimefun, but another plugin might do it).

Here are a few things you should do or answer to in order to see what's really wrong : 
1. What Skyblock plugin are you using? (ASkyBlock has its own protection handling, which doesn't affect Slimefun, but uSkyblock uses WorldGuard, which might (i'm not sure))
2. Run a clean test server with Slimefun and CSCore-Lib installed. Does the bug occur?
3. Run a copy of your server and remove each "unrelated" plugin, one by one, until the bug vanishes.

**Comment by AtomicScience** [comment]
I encouraged the same bug and, I think, the reason of it is AntiFastBreak, which is included in almost any anti-cheat. CSCoreLib breaks block on behalf of the player and anti-cheat cancel event.
So, related methods in CSCoreLib must be rewritten with using .breakNaturally() or .setMaterial(Material.AIR)

**Comment by BlackBeltPanda** [comment]
AtomicScience is correct. After testing on a clean server and loading plugins individually, the culprit was AAC, my anti-cheat plugin.

**Comment by TheBusyBiscuit** [comment]
The Saw Mill (and possibly other blocks) should switch to CS-CoreLibs protection handler rather than just calling an event, marking it as a Bug Report therefore.

**Comment by AtomicScience** [comment]
Well, also I noticed some problems with Slimefun jetpacks - some anti-cheats consider what player use Fly cheat and kick or even auto-ban him. I'm not ensure this bug exist, but...
So, Slimefun or/and CSCoreLib must integrate with anti-cheat to prevent this issues

**Comment by madolebr** [comment]
hey, the way i got around this was just tweaking the antiblockbreak in the anticheat plugin. i used ncp and cncp, and was able to change it to where it works 98% of the time

**Comment by TheBusyBiscuit** [comment]
Adressed in #674 and in later builds:
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master
