### ISSUE TITLE
CSCoreLib's Head with every head break using Slimefun

### ISSUE THREAD

**Issue by Coolkc456** [TheBusyBiscuit/Slimefun4#584]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Everytime someone breaks a Slimefun Exotic Harden head, CSCoreLib's head drops with it.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/7k8RYDg5

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
http://prntscr.com/i7bmd4
http://prntscr.com/i7bmo6

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
Craftbukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.13
ExoticGarden v1.6.3

**Comment by AtomicScience** [comment]
It seems that ExoticGarden's data about fruit trees location was damaged, and now if you break heads pluign don't count them as fruits and don't drop correct items instead of broken heads - probably you did something wrong, for example, damaged files in 'data-storage' folder or stopped server at an nopportune moment - try to load Slimefun backup from 'data-storage/block-backups'
