### ISSUE TITLE
New Research System

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/Slimefun4#585]
I find the default research system to be grindy and not that all interesting.

Heres a idea I came up with which should be a option in the near the future if anyone is willing (I might be, but my java skills are still noob level):

1. Open slimefun guide and go to a locked item, click it to get a blueprint (optionally cost XP or money)
2. Place down the Research Table multiblock structure and put the blueprint in it
3. Supply the blueprint with various items and xp depending on what the item is (like if its a ingot supply some iron and other things)
4. Click the research button to start researching (same type of time system as auto enchanter, but depending on blueprint difficulty will change the amount of time it takes to research)
5: On output slot will be New Research item (or some type of name like that). You just right click it in your hand to unlock said research

I think this idea would be a really neat way to research, it sorta keeps the grind but makes it more fun in my opinion.

**Comment by AtomicScience** [comment]
Thank you for idea, but there are few problems which make it little hard to make:

1) Lots of blueprints and "New Research" items should be registered for every Slimefun item
2) Multiblock structures can't contain items and process things as electric machines do
3) Every blueprint should contain lore, name, XP count and required items - all this data will take up a lot of space and must be created manually

So, this idea will take much time to embody and will not change gameplay at all - instead of immediate researches players'll just wait a little.
Also, hard researches will demotivate players to craft new mechanisms

**Comment by xH3LLRAIZ3Rx** [comment]
1. Didn't really think of that
2. true
3. it wouldn't show that info in the item, the item would just have a name, and the lore would be what research its for, when putting the item in the table, it would show a GUI item that has a list of whats needed

Also I did not really think about it, maybe no timer, just items needed.

Also to remedy the first thing, it might be possible to create one item and put a var for the lore of the research.
