### ISSUE TITLE
Error while creating new Addon

### ISSUE THREAD

**Issue by peterpotato** [TheBusyBiscuit/Slimefun4#593]
## Description
I wanted to extend SlimeFun4 with a custom plugin, as shown in your turorial here: https://github.com/TheBusyBiscuit/Slimefun4/wiki/API. Since I have no experience in coding plugins for Bukkit, I used this guide by Bukkit: https://bukkit.gamepedia.com/Plugin_Tutorial. Everything went fine during programming. But there's one error I don't know how to solve. When I register my Item (Apfelwein), this showed up: "Syntax error on token "register", Identifier expected after this token." I sticked to your given guide, but I don't know how to handle this error. I have included a screenshot.

## Server Log
https://pastebin.com/M1E1bKDg

## Evidence / Proof
http://b9.eu.icdn.ru/s/stafflecraft/4/imgsrc.ru_58300654pHc.jpg
-A screenshot of my (small) code

## Environment
Minecraft 1.12
CraftBukkit v1_12-R1

CS-CoreLib v1.5.16
Slimefun v4.1.13

Installed Addons:
ExoticGarden v1.6.3

Thanks,
peterpotato

**Comment by xH3LLRAIZ3Rx** [comment]
The first problem is in the log it shows your plugin doesn't have a valid plugin.yml

To fix that problem, it seems like you're not using the right identifier, instead of research.register(); you need to use the SlimefunItem item you made, so basically like this:

SlimefunItem apfelwein = new SlimefunItem...

apfelwein.register(); -> to register item

Research Ers = new Research...
Ers.register(); -> to register research

also don't forget to add: Ers.addItems(apfelwein); to register the sf item under the research
