### ISSUE TITLE
Ancient Altar not working?

### ISSUE THREAD

**Issue by MFarhanA** [TheBusyBiscuit/Slimefun4#612]
## Description
I tried to construct ancient altar just like the demonstration https://youtu.be/mx2Y5DP8uZI but for some reason, it didn't work at all. It will only let me open the Ancient Pedestal just like opening a normal dispenser when I right-click on it same thing with the Ancient Altar. Do I have to build it in the sky like in the video? (which I personally believe it doesn't matter at all) or do I have to build it in an open area without any block above it? (since I tried to construct the altar under the mob XP farm)

## Server Log
I don't have access to server log as I'm only a player.

## Evidence / Proof
https://youtu.be/rPlHEcXmW40

## Environment
Minecraft Version: 1.12.2
CS-CoreLib: Unkown (I believe, only the server owner can see it)
Slimefun: v.4.1.13 (Also I don't have permission to run /sf versions for some reason)

**Comment by AtomicScience** [comment]
I think you should report this issue to your server administrator, not directly to us

**Comment by comfuzzled** [comment]
On the server I play, the thing works for everything exept for ender pearls. The ender pearls won't go on the pedestals, which sucks because the main reason I made it was for the elytra, and that needs ender runes.

**Comment by mrcoffee1026** [comment]
To original poster: you might have to actually right click with the appropriate item... however if you're opening a dispenser, then you may have lost your actual pedestal.  They are prevented from opening as "normal" by Slimefun... at least in every build I've ever used.  There might be a way to circumvent this action with - yet another - plugin, but I'm not sure what your server guy could have installed that would do that.

Comfuzzled -- I believe the enderpearl issue was resolved many, many builds ago.  Last one I was aware of was the empty flask of knowledge in the elytra recipe... wherein it was virtually impossible to place on the padistol without loading it with exp and making it the wrong ingredient... but I thought I read a build that resolved that issue too later.

In any case both servers may need to verify they have a later build on since I don't think either issue exists right now.  You can still "miss" the target and toss an enderpearl instead of placing one... but I I don't think it matters where you click on an actual pedestal, It won't provide you with a dispenser interface.  And no, you do not have to build the thing with sky access... I do not - however - advise building one on top of or underneath a mob farm because entity lag could result in unexpected behavior... like the blocks losing their SF properties and becoming vanilla blocks, for instance.

**Comment by mrcoffee1026** [comment]
I later experienced this myself on my own server in the case that I'd restored a slimefun data file backup... the placed items left behind in the world happening after the backup had been made, the items themselves were not longer Slimefun items... just dispensers and an enchantment table with colored titles that did nothing special.  The simplest solution to the problem you're describing is replacing the items with new ones and see if the issue persists.

**Comment by madolebr** [comment]
also if the server administrator has disabled the latar and pedistals due to the dupe glitch, they will open like normal dispensers instead

**Comment by comfuzzled** [comment]
Thank you. I will ask if the admin has disabled it and get back to you as
soon as possible.
