### ISSUE TITLE
Trash can and Cargo output

### ISSUE THREAD

**Issue by Erwanger** [TheBusyBiscuit/Slimefun4#644]
Hello.

I thought that we could attach an Advanced Output Node, or even an Output Node, to a Trash can, but I can't do it.

Is it normal?

It's not really an issue, just a question.

Thanks!

**Comment by AtomicScience** [comment]
Nodes can work with Trash, but you can't place them directly to it because you can place them only AT vertical faces of blocks. Probably, it's bug, but i'm ensure it'll be quite hard to fix it.

You can bypass this bug/feature. Just follow these steps:
1) Place any block where you want to place Trash
2) Place Node at this block
3) Replace your block with your Trash

**Comment by Erwanger** [comment]
Ok I will try it, thanks!
