### ISSUE TITLE
Bug invisible items and disapair items with hand, and chests.

### ISSUE THREAD

**Issue by infinity3113** [TheBusyBiscuit/Slimefun4#650]
## Description

Hello, I have a very serious problem with the slimefun, several users on my server complain about lost objects, items both hand and floor, chests, and invisibility when entering an area that has exotic garden, I realized that the lost objects of the chests, they are near machines of the slimefun, but it is not a single item, if not several ex:

Screenshot section.

Everything contained in the chests near the slimefun are erased just as when they are thrown on the ground they are often hidden. I would like help because my users complain a lot every day.

## Server Log
no need

## Evidence / Screenshot
https://imgur.com/a/t6vBn

## Environment
Spigot 1.11.2 latest build tools
Slimefun: 4.1.14
Cs-CoreLib: 1.5.16
ExoticGarden: 1.6.3

**Comment by mrcoffee1026** [comment]
This problem is coming from harvesting of the slimefun exotic garden plants... it will persist within the chunk the plants reside in until the plant has regrown.  I'm not sure what the "exact" cause is but it does seem to be lag-related.  Also use of electric machines and cargo networks within a chunk can also cause the disappearance of entities.  The solution is to DO NOTHING in the chunk until the plants have grown, machines have finished their tasks, etc.  At this point, leave and reload the chunk (sometimes even f3+a will suffice) by teleporting far, far away and then returning to the affected location a short time later.  Do NOT attempt to break/replace blocks that are "missing", they are not missing, just invisible... and if you successfully break an invisible block you will not necessarily retrieve that blocks contents.  This affects all entities, though I've never seen it affect a chest.  Item frames, minecart+anythings, mobs, even players.  Usually players reappear simply by leaving the affected chunk (and disappear again if reentering the toxic slimefun plant chunk).  I Advise limiting exotic garden plants to chunks which you will not be placing mob farms or building slimefun electrics / cargo networks.  They do not play nice with each other at all.  I've been able to get away with some limited cargo use in a chunk that has things like item frames for a chest shop, but there does seem to be some kind of limitation as to how many entities and cargo things can be in a single chunk at a given moment - AND still work as expected.  There might be some kind of efficiency overhaul this plugin and the Exotic Gardens addon could undergo at some point, but even if it did, that limitation would probably still remain, so the best approach may be to work around it by quarantining the exotic garden bush farms to chunks where that's all that's happening in those chunks so that they don't interfere with inventories and other slimefun equipment.

**Comment by infinity3113** [comment]
We updated to version 1.12.2 and we were in this version for two weeks. And I did not have any of the problems that I mentioned before. Do you think it's due to the version?

Only that I had to go back to version 1.11.2 due to ram problems and stability.

**Comment by mrcoffee1026** [comment]
naw i mean I've seen it in every version including 1.12.2... i mean maybe some of the blocks glitched to CSCoreLib head's... that would have also "solved" your problem, but it seems to me the chunks can only handle so much crazy stuff going on in them at any point in time... I believe the bush skull plants sort of count as entities too which might have something to do with it... I do know trying to mob farm in the same chunk where electrics or plants exist is nearly impossible since... the mobs will disappear and a player can't hit an invisible mob... maybe a later build is working a little better now but even today I had a guy trying to build his electrics over a golem spawner he set up and his slimefun blocks kept glitching into their vanilla counterparts instead of remaining the machine blocks he built.  I think regardless of ram, this is going to just constantly be an issue.  We're on a dedicated server with SSD and everything, it's either too much throughput for the plugin itself to handle, or possibly for any world to keep up with.  I can't offer a perfect solution but I've been able to get away with a lot more just by placing things like bush grows in a chunk by itself... and the crazier portions of any electrics into a chunk off by itself.  I kind of need cargo scattered around all over but so long as do those other two things they don't seem to be as troublesome either.  Like I use cargo equipment in my mob grinders and they don't vanish the mobs in any of them regardless of how "busy" the grinders are being used.   If switching versions helps you that's cool but... the problems you run into really don't happen except when those plants are being harvested (and the time it takes for them to grow back) or you're doing a bunch of electrical processing anyway, so I don't think the version can be pointed at unless when your players use their equipment and harvest their plants again that the problem has truly gone away.  Anyway, usually if they build with that issue in mind, the problem solves itself for the most part... they just want to really well light the builds for the plants and electrics since mobs can and will still vanish in those chunks while they're in use.  A visit by an invisible creeper can really wreck a guy's day.

**Comment by LoXR** [comment]
Also having this problem on 1.12.2, if you use React, and it can that causing the problem aswell.

**Comment by mrcoffee1026** [comment]
Yeah i don't have React, I think it's just something about having too many entities in the same chunk or... just slimefun specific entities of a certain number in the chunk may cause it, I'm not certain.  It's important to be aware that - while invisible -they do still exist.  I once tried to like replace a bunch of "missing" minecart hoppers... the result of doing so was that portions of inventory would be "lost" into the invisible minecart hopper - which was still there, just inaccessible.  Then later... after machines had stopped running or plants had stopped growing... everything would be recoverable but if you - as I had - taken steps to replace the "missing" items... I did all that for nothing, and now had twice as many of everything.
