### ISSUE TITLE
[Eclipse SF Testing] I needing help for making an Item

### ISSUE THREAD

**Issue by xLastt** [TheBusyBiscuit/Slimefun4#652]
## Description
¡Hmm Hello!
I am trying to make an object that contains some enchantments but at the same time that these enchantments be hidden, also that item be indestructible and that also be hidden that option

## Example
Slimefun Setup:

> new SlimefunItem(Categories.TOOLS, SlimefunItems.TESTING1_PICKAXE, "TESTING1_PICKAXE", RecipeType.ENHANCED_CRAFTING_TABLE,
> new ItemStack[] {SlimefunItems.COBALT_INGOT, SlimefunItems.COBALT_INGOT, SlimefunItems.COBALT_INGOT, null, SlimefunItems.COBALT_INGOT, NICKEL_INGOT, null, SlimefunItems.NICKEL_INGOT, null})
> 		.register(true);

Slimefun Items:

> 	public static ItemStack TESTING1_PICKAXE = new CustomItem(Material.GOLD_PICKAXE, "&f&lA TEST", 0, new String[] {"","Lore2","Lore3","Lore4","Lore5"}, new String[] {"ENCHANT1-LEVEL", "ENCHANT2-LEVEL"});

## What i need to do?
Im tried to put "Unbreakeable/Hidde" at Enchant lines but that don't works...

## Environment
Last Versión

**Comment by xH3LLRAIZ3Rx** [comment]
the enchant level is for enchantments only, if you wanna do things like hide enchants your gonna need to use your own way of making a item. If you want to just add for example Unbreaking you put DURABILITY-levelint in the enchant strings. Also, its best to make your own addon rather than editing slimefun itself so that you don't have to manually add the changes of slimefun in, unless you're using git, but its still better to make your own addon.
