### ISSUE TITLE
how to repair items slimefun lost when restart / crash

### ISSUE THREAD

**Issue by icansc187** [TheBusyBiscuit/Slimefun4#668]
how to repair items slimefun lost when restart / crash

**Comment by VoidAngel** [comment]
There isnt currently a fix for data corruption/saving issues.
Although if I knew how to fix it I would personally x'D

There are two ways that I know of to help lessen the impact of the issue. Sadly they are kind of.. well... inefficient and actually just "band aid" fixes. These patches also create even more possibilities for exploits within slimefun and other plugins.

The first and easiest bandaid fix would be this plugin
https://www.spigotmc.org/resources/changebackitem.4713/

Again, as I said, this is risky, not a proper fix, and is untested, but it may help with your immediate problems.

As for the second method I think Im just going to leave it out because its likely that the above plugin would be a better choice.

**Comment by icansc187** [comment]
thanks :grin:
