### ISSUE TITLE
Ignition Chamber Lag

### ISSUE THREAD

**Issue by realchessx** [TheBusyBiscuit/Slimefun4#715]
## Description (Required)
Ignition Chamber LAG

## Evidence / Proof (Required)
https://timings.spigotmc.org/?url=yelepifihi
http://prntscr.com/jv5sp2

## Environment (Required)
slimefun 4.1.15
cs-corelib 1.5.18

**Comment by madolebr** [comment]
you do have some lag due to the ignition chamber,, but u need to do more work to your server in general to get rid of your massive amounts of lag. install react and limit mobs, or something, because u are getting town up with entity movements. reduce view distance and entity activation range

**Comment by TheBusyBiscuit** [comment]
Whoever added the Ignition chamber (I didn't even know such a thing existed) didn't really design it carefully.
It should be improved for sure.

https://github.com/TheBusyBiscuit/Slimefun4/blob/183a34a99c1d46b1223f7360bbb40f0aa408141c/src/me/mrCookieSlime/Slimefun/listeners/ItemListener.java#L74

**Comment by Poslovitch** [comment]
I will have a look at that thing.

**Comment by andris155** [comment]
Use Paper and optimize your server!

**Comment by Poslovitch** [comment]
PaperSpigot has a lot of breaking fixes for a month or two. I wouldnt recommend using it anymore with Slimefun

**Comment by andris155** [comment]
I don't like Spigot because use old timings and not available hopper optimization.

**Comment by madolebr** [comment]
i use paper spigot personally and have less sf bugs because of it, along with great improvement in performance

**Comment by realchessx** [comment]
kk thanks for the advice, paper spigot is not applicable to my server, it corrupt or show error more than it fixed the lag, i tried to optimize more spigot setting it reduce some lag, i still get ignition chamber lag

**Comment by mrcoffee1026** [comment]
The ignition chamber suffers initially by creating an open/active hopper situation, place chest upon it to at least partly solve the issue... but the other thing is that it reveals itself in timings where using an observer and redstone to trigger a dispenser for reignition does not.  The only "design flaw" I'm able to come up with is that the ignition chamber reignites on EVERY use, whether or not the fire has actually gone out... as there is nothing to tell it if the fire is out or not, it fires anyway.  Using an observer will also cause "some" click lag as it "observes" no only the fire going out and the fire being reignited... but also every stage of the animation of the fire... of which I've counted about 15 audible "ticks" as it detects them... takes nearly a full minute to cycle through them all.  The least laggy method I've found for reignition is using a vanilla redstone block update detector which will fire only when the fire goes out... and when the fire reignites... although the secondary firing does not cost any durability to the flint & steel since the fire is already lit.  Even this approach, during its use... will result in enormously high redstone click counts... but they're limited to "during its use".  Replacing the ignition chamber with those sorts of alternatives will remove it from the timings list... however, you'll still get the same slowdowns when players get into a production run do the constant clicking / reigniting until they finish... it just won't be on the list anymore.  At that point you'll need some kind of secondary tool like Redstone Clock Detector to be running while they're using it in order to track it.

I think this device would likely be laggiER if some coding was added to check for the fire being lit or not.  But as I'm unlikely to get players to follow a simple protocol like "put a chest on top" of this device in order to use it... the open/activated hopper lag they add... one block at a time... to the server is enough for me to want to disable the item entirely.  However there is probably no way of removing it from the timings list without simply removing the block from every build.  There are very few people that use slimefun and smelt one ingot at a time... nearly everyone will be smelting stacks of materials which will result in excessive "clicking" and adding to the timings list.  It's just the nature of what is going on.  Replacing it with something else won't make the lag go away, it will just hide the lag as something else doing it.  You could convince all users to switch to electric... and cargo... and eventually get that lag moved into the cargo network instead, but it will still be present.

**Comment by AtomicScience** [comment]
I'll fix it, don't worry
