### ISSUE TITLE
[Suggestion] About the texutures of SlimeTech4

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [TheBusyBiscuit/Slimefun4#717]
Hi, I'm a user of SlimeTech4.
Today I wondered if there is a way to add extra textures because ST4's textures are using default one of Minecraft.
Then I searched on the Internet and then find a good and runnable way to make it come true:
Minecraft has an issue that items that you can get extra data values with only one data value.
e.g: If I input /give <username> bone 1 1, then it'll give the player the bone that has no any textures.
With this issue, I think you can try to optimize the texuture of each item in ST4(Especially the food that uses the skull blocks).
And for last, hope to see a better and more gamer-oriented plug-in!
Thanks

**Comment by SoSeDiK** [comment]
You can't make textures using the data values. In vanilla, it's only possible with [these items](http://accidentalgames.com/media/durabilityModels.php) by changing their "per durability models". However, this feature has many bugs and there are many things that you should take care of. I'm pretty sure that no one will even try to do this with Slimefun. Also, not every player wants to install a resource pack.
I can suggest you use OptiFine CIT feature. It's easy to understand and you can do something like this:
![Slimefun](http://picua.org/img/2018-06/15/4sgi6d7oqeq2ybjfdb47laj7x.png)
Btw, I added a lore "§0sf:item_id" to every item in SF, so textures are also made by their lore. This also allowed to recognize an item even if player changed the item's name or added some enchantments or do whatever else. And I can change items in sources any time I want without breaking those that are already in use.
You can do the same thing or use their names since there are no item hashing for now.

**Comment by TheBusyBiscuit** [comment]
This is "Slimefun" not "SlimeTech"...
Also, this is not a relevant Bug report.
