### ISSUE TITLE
Duplicating items using Talisman of the Hunter and llamas/donkeys

### ISSUE THREAD

**Issue by Firebuggie** [TheBusyBiscuit/Slimefun4#729]
## Description (Required)
Talisman of the Hunter allows to duplicate items placed in inventories of tame llamas and donkeys.

## Server Log
n/a

## Evidence / Proof (Required)
![ezgif com-optimize 2](https://user-images.githubusercontent.com/40775637/42188925-400482a2-7e56-11e8-9063-484d4db9b3b0.gif)

## Environment (Required)
CraftBukkit v1_12_R1
CS-CoreLib vv1.5.18
Slimefun vDEV (48)
Installed Addons (0)

**Comment by Poslovitch** [comment]
The problem here is that it is somehow an intended feature...

**Comment by TheBusyBiscuit** [comment]
@Poslovitch I don't imagine anyone is happy with this being a possibility.
But I don't know whether there is a way to distinguish between mob drops and chest content drops, because Spigot only passes an ArrayList that contains both.
A LUT would be very bad, special cases for chest-ed animals are the only option available I presume.

**Comment by Simom100** [comment]
If the mob is an "instanceof ChestedHorse" then you can call "isCarryingChest()" whitch returns true it there is an chest equipt.
