### ISSUE TITLE
Slimefun has completely stopped working.

### ISSUE THREAD

**Issue by EnderHater** [TheBusyBiscuit/Slimefun4#821]
## Description (Required)
Slimefun has completely stopped working for no reason.

## Server Log
https://pastebin.com/iy9Krkna

## Evidence / Proof (Required)
I'm not a YouTuber so no videos are provided. All I can say is that Slimefun apparently errors when I place any sort of custom block down.

## Environment (Required)
The latest version of the 1.1`2.2 version of both Slimefun and CS-CoreLib.

However, certain items DO work when not in custom worlds such as while in a TARDIS world (Using the latest version of the TARDIS plugin for MC 1.12x).

**Comment by EnderHater** [comment]
I bet mrCookieSlime ain't gonna answer.

**Comment by MothGirlMusic** [comment]
1.12.x hasn't been worked on for a while. so its not something that was suddenly changed on slime fun's side. if you downloaded it from the build website, they're all 1.13.x builds now... so it comes down to "where did you even get the file from? how long has it been in your server? did it ever work or did you get the wrong .jar? and what did you do that caused it to stop working? settings edited? plugin added?

**Comment by MothGirlMusic** [comment]
because the plugin works in the vanilla world, i'd say its an issue for multiverse. for some reason its not loading itself first before your copy of slime fun. then again, md5 says himself, the dependencies are just a suggestion when booting up the server. there's no promises kept. so maybe you just have too many plugins for your server to keep up with.

**Comment by EnderHater** [comment]
> because the plugin works in the vanilla world, i'd say its an issue for multiverse. for some reason its not loading itself first before your copy of slime fun. then again, md5 says himself, the dependencies are just a suggestion when booting up the server. there's no promises kept. so maybe you just have too many plugins for your server to keep up with.

I have 4 GB, and I'm only using Slimefun with CS-CoreLib, latest 1.12x builds.

**Comment by EnderHater** [comment]
> 1.12.x hasn't been worked on for a while. so its not something that was suddenly changed on slime fun's side. if you downloaded it from the build website, they're all 1.13.x builds now... so it comes down to "where did you even get the file from? how long has it been in your server? did it ever work or did you get the wrong .jar? and what did you do that caused it to stop working? settings edited? plugin added?

I think if your smart enough you could release a build that has legacy support.

**Comment by MothGirlMusic** [comment]
@jeddell i have a bungee cord set up with multiverse and slimefun on all my nodes [except minigames] and they're all 1.13.2  and all of them work. period. i have exotic gardens, barrels, and all that working as well. i downloaded from this GitHub.. so its NOT slime fun's fault for not working, because i'm on 1.13.2 and it does, on all worlds on my servers. vanilla and not. you can see why i assume multiverse is not getting loaded, then again, its an easy check if you open up plugin.yml in the .jar [use winzip or something and soft-depend it... then tell me whether it is or not.]

**Comment by comonier** [comment]
@EnderHater  @jeddell  @MothGirlMusic 
update new builds from here:
https://thebusybiscuit.github.io/builds/
