### ISSUE TITLE
Energy regulator corrupt on Nuclear Reactor explosion

### ISSUE THREAD

**Issue by sarhatabaot** [TheBusyBiscuit/Slimefun4#892]
## Description (Required)
Energy regulators corrupt when an explosion occurs. Making it impossible to place a new regulator in their place.
Also causes a NullPointerException as described by the error file below.
## Server Log
Error file: https://pastebin.com/nHtVGawW

## Evidence / Proof (Required)
https://prnt.sc/nc4sau

## Environment (Required)
  + Spigot 1.13.2-R0.1-SNAPSHOT
  + CS-CoreLib DEV - 36 (git 2e140f82)
  + Slimefun DEV - 91 (git 9436c3d6)
  + Essentials 2.16.1.0
  + SlimefunOres 1.4.7
  + EssentialsSpawn 2.16.1.0
  + EssentialsChat 2.16.1.0
  + SlimefunLuckyBlocks 1.1
  + ExoticGarden DEV - 8 (git 20923cd3)

**Comment by mrcoffee1026** [comment]
Besides nuclear meltdowns there's many other things that can cause the corruption of that block, so it's super helpful to have a staff equipped with kill permission so they can /minecraft:kill @e[type=armor_stand,limit=1] while standing right by it.  This will kill the invisible armor stand and allow you to place blocks there again.  They might be able to build something into the plugin to more completely destroy the item, but since there was a nuclear "explosion"... I wouldn't expect the material to last for additional uses.  There aren't a lot of ways that I know of for non-admins to get rid of invisible armor stands but you can move them if you get real desperate.  I've had some luck shifting their location with pistons and either pushing them into a wall or just glitching the item onto the surface of a piston so that it could be mined, although that's less reliable.  Kill command is the most reliable... you could also search the actual ENERGY_REGULATOR.sfb file and remove the block address still listed in that block's location... after a restart it should go away.

**Comment by sarhatabaot** [comment]
Sure. We also found a way around this using a flint and steel. 
However the issue (#893 ) this is caused from in the first place is much more worrying, as of right now we've informed all our users to not use any generator except solar.

**Comment by mrcoffee1026** [comment]
Well as far as I know all generators do keep up their production until the fuel is used up whether or not there is a machine attached to the network... that's why I recommend capacitors even with something like a coal generator.  The nuclear one is the only one that will suffer from meltdowns if you don't keep it constantly filled with coolant, but if you want to "shut it off" you'd have to remove it's source of fuel.  As that's always been true I don't think that's a bug, just the way those work.  I have never recommended nuclear or nether star - myself - just due to the hassle of keeping them loaded with materials... and the result would be producing well over any quantity of power any 5 combined end-game players would even need, there doesn't seem to be a "worth it" for this once you've sorted out all the materials you need to collect and continue to collect to keep it operational.  And yeah flint/steel would work unless you've got fire-tick/spread shut off which I do.

**Comment by sarhatabaot** [comment]
It hasn't been that way. It's new, with nuclear reactor's especially, it's supposed to shut-off when there isn't a machine on the network. See [this image](https://puu.sh/DgOu0/c748866c44.png)
We didn't have this issue until we updated to the 1.13 version. But I'll look into previous versions to see if this was on other generators and we just missed it.
