### ISSUE TITLE
Electric Furnace cannot smelt 1.13 log items Sawmill cannot chop 1.13 log items

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/Slimefun4#894]
## Description (Required)
Log items all have new ids.  I'm not sure if the intention would be to duplicate vanilla behavior... but in vanilla behavior every version of log will produce a charcoal lump: stripped_oak_wood, stripped_oak_log, oak_log, oak_wood... for each flavor of tree.  None of these items smelt in the electric furnace.

Would Expect the same items above to also be accepted as "log" for the Sawmill although none of these items work there either.

## Server Log
No errors in logs just items not working as expected.

## Evidence / Proof (Required)
![2019-04-15_21 07 14](https://user-images.githubusercontent.com/3322491/56174894-c5e62800-5fc2-11e9-9cf5-12767e76e6ed.png)

## Environment (Required)
[21:03:22] [main/INFO]: [CHAT] Paper v1_13_R2
[21:03:22] [main/INFO]: [CHAT] 
[21:03:22] [main/INFO]: [CHAT] CS-CoreLib vDEV - 36 (git 2e140f82)
[21:03:22] [main/INFO]: [CHAT] Slimefun vDEV - 92 (git 4f05f804)
[21:03:22] [main/INFO]: [CHAT] 
[21:03:22] [main/INFO]: [CHAT] Installed Addons (2)
[21:03:22] [main/INFO]: [CHAT]  ExoticGarden vDEV - 8 (git 20923cd3)
[21:03:22] [main/INFO]: [CHAT]  SoulJars vDEV - 1 (git 3c1e410e)

**Comment by xH3LLRAIZ3Rx** [comment]
This bug is happening in 1.14 as well

**Comment by dniym** [comment]
The sawmill requires a block to be placed on top of it, this with the current way slimefun is coded made changing the existing sawmill a very tedious change.  Thus the sawmill has been replaced with the Table Saw in 1.14.

However; 1.13 versions aren't being updated any further..  The new 1.13 blocks logs / stripped logs etc have been fixed in later versions although there is no guarantee a newer version of slimefun built against 1.14 will work correctly on 1.13, obviously the table saw wont work on 1.13 as it uses a 1.14 block.

Also added a PR to fix the logs not working in the furnace.  Please try to make a separate issue per actual issue you have with different items, this should have been two different tickets.
