### ISSUE TITLE
Slimefun lag and maybe memory leak

### ISSUE THREAD

**Issue by Leomelonseeds** [TheBusyBiscuit/Slimefun4#906]
Recently, I have noticed that slimefun has been causing tons of lag on my server.

Below is a screenshot of proof:
https://gyazo.com/2af561dc0df86d8f23874b9cb7ef2eb7

I believe the lag is caused by massive cargo systems. Setting the custom-tick-rate to 20 from 12 in the config didn't seem to do much.

There also seems to be a memory leak. I could not identify which plugin it was from, but I pinned it down to either StackMob or Slimefun, as they use many resources to cache data.

If you could help, that would be great.

Thanks!

**Comment by TheBusyBiscuit** [comment]
Closing this, since it is not an actual Bug Report.
I'm not saying there wouldn't be an issue with it.
But Slimefun4 is just a very intensive plugin and there isn't really much that can be done other than remaking the entire project.

A memory leak on the other hand is fixable of course, but then again "there seems to be a memory leak" is not enough information at all and I don't think there even is a way to realiably track that down.

**Comment by shieikhamir-crypto** [comment]
Hello, my Minecraft server is very laggy. What can we do to replace the cargo mangement section?
