### ISSUE TITLE
MySQL/Sqlite Databridge

### ISSUE THREAD

**Issue by Imothep80** [TheBusyBiscuit/Slimefun4#95]
## Description
Currently all data is saved local in drawer data-storage.
if it possible do store data to MySQL/Sqlite?

So any user can use the knownledge to every Server. I think it just needed the uuid.yml stored to database. Maybe the inventory too, but blocks are Server/world based. Or not?

**Comment by TheBusyBiscuit** [comment]
Its planned since months but always delayed since there is not enough demand for it.
https://github.com/TheBusyBiscuit/Slimefun4/milestones

> So any user can use the knownledge to every Server. I think it just needed the uuid.yml stored to database. 

That is about as wrong as you can be. Never ever make claims like this in front of anyone who has even the slightiest experience with DB Management.

I had to set up databases for some video game companies before, believe me...
Databases are the WORST and most difficult part of the IT branch of all time, implementing databases properly is just as enjoyable as combing your hair with a mace.
So adding database integration does not make too much sense unless there are enough people out there who want this.

**If you want to see MySQL Integration, then please leave a thumbs up for this issue**

**Comment by Imothep80** [comment]
Okay. I believe you that it is really complicate to develop. Thank you for the explain. :)

You say this feature is still in your task so i think i can close it.

**Comment by TheBusyBiscuit** [comment]
Read my comment... -.-

**Comment by NathanAdhitya** [comment]
Hmm, Good idea. But is MySql Really that hard?

**Comment by AlexLander123** [comment]
Would love to see it happen. But database are hard to implement. It most probably require a restructure of the data saving system and handling migration from flatfile to database is also a problem.

**Comment by WindUnwaken** [comment]
How about only store research in mysql? Players only care about their research, as we know, standard server can't hold over 60 players with 20.0TPS.

**Comment by Poslovitch** [comment]
I'm working on that right now

**Comment by lukemango** [comment]
any progress on this?
