### ISSUE TITLE
Cant see items IDs?

### ISSUE THREAD

**Issue by Azrath** [TheBusyBiscuit/Slimefun4#98]
## Description
Cant see items IDs? I am sorry for posting this here but I do not know where else to post and I need item IDs so I can include them in starter kit and donator rewards! Hope you can help! 

## Server Log
No problem in server log.

## Evidence / Proof
WhatIsIt plugin shows only normal minecraft item IDs of items.

## Environment
Everything latest.

**Comment by NathanAdhitya** [comment]
Slimefun doesn't use any type of IDs, they use Item Meta-Tags instead. Try using a plugin where you can also drag-and-drop those items, since Slimefun relies on those tags. Like, what makes a machine a machine is their metadata not their id.

Solution for StarterKits: Get a plugin that lets you drag and drop items in to it.

**Comment by FrostExZo** [comment]
ehm... /sf give u cant add in starter kit?

**Comment by NathanAdhitya** [comment]
Frost, good idea. Try adding commands with it. /sf give was a good idea. Thanks Frost. :P

**Comment by Azrath** [comment]
I could use it like 1 year ago, what happened now? Also could use IDs to sell lucky blocks too!

**Comment by NathanAdhitya** [comment]
Are you sure it was Slimefun? Slimefun never had IDs for them. It's all meta tags since the beginning. Adding new IDs isn't possible in non-modded minecraft.
